import { useContext } from 'react';
import 'react-responsive-modal/styles.css';
import { Modal } from 'react-responsive-modal';
import GlobalState from '../../context/GlobalState';
import { Description, Heading, Subtitle } from './Modal.style';

interface TextsType {
  description: Array<{title: string, value: string}>
}
export const ModalComponent = ({ type }: {type: string}) => {
  const { modalType, setModalOpen } = useContext(GlobalState);

  const { lang } = useContext(GlobalState);
  const isPl = lang === 'pl';

  const getPolishTitle = ():string => {
      if(type === 'immigrants'){
        return 'Cudzoziemcy: pobyt i praca'
      } else if(type === 'polish-courses') {
        return 'Kursy języka polskiego'
      } else if(type ==='passport') {
        return 'Obywatelstwo polskie'
      } else if(type === 'business') {
        return 'Biznes'
      }
      return 'Inne'
  }

  const getEnglishTitle = ():string => {
    if(type === 'immigrants'){
      return 'FOREIGNERS: RESIDENCE AND WORK'
    } else if(type === 'polish-courses') {
      return 'Polish language courses'
    } else if(type ==='passport') {
      return 'Polish citizenship'
    } else if(type === 'business') {
      return 'Business'
    }
    return 'Other'
}

  const getPolishTexts = (): TextsType => {
    if(type === 'immigrants'){
      return {
        description: [
          {title: 'Wizy', value: 'Jeśli nie korzystasz z możliwości wjazdu w ruchu bezwizowym możemy pomóc Ci w uzyskaniu wizy. Przygotujemy wniosek, zarejestrujemy w systemie, udzielimy wszelkich niezbędnych informacji. Jeśli planujesz dłuższy pobyt możesz go kontynuować na podstawie pobytu czasowego.'},
          {title: 'Zaproszenia', value: 'Jeśli nie korzystasz z możliwości wjazdu w ruchu bezwizowym, ale chcesz przyjechać na rozmowy handlowe, wziąć udział w targach lub odwiedzić krewnych to będziesz potrzebował zaproszenia oraz wizy. Wymaga to zaangażowania i czasu, którego często nie mamy dużo. Możemy pośredniczyć w uzyskaniu zaproszenia, zajmiemy się wszystkimi formalnościami. Mając zaproszenie będziesz mógł ubiegać się o wizę. Jeśli potrzebujesz naszego wsparcia, chętnie Ci go udzielimy.'},
          {title: 'Karta czasowego pobytu', value: 'Zakładamy, że jesteś w Polsce na podstawie wizy, ruchu bezwizowego albo zezwolenia na pobyt czasowy i chcesz przedłużyć swój pobyt. Właściwym krokiem będzie ubieganie się o zezwolenie na pobyt czasowy i kartę czasowego pobytu. Nie jest to łatwe, a dla wielu Cudzoziemców stanowi nie lada wyzwanie. To jest ten moment, kiedy powinieneś zastanowić się nad przekazaniem prowadzenia sprawy doświadczonemu doradcy który pomoże Ci uzyskać kartę czasowego pobytu na okres nawet do 3 lat, zwłaszcza jeśli w perspektywie chcesz uzyskać stały pobyt.'},
          {title: 'Łączenie rodzin', value: 'Jeśli pozostawiłeś w ojczystym kraju najbliższą rodzinę albo rodzina przyjechała do Polski i chce z Tobą zostać, a Ty posiadasz zezwolenie na pobyt czasowy od co najmniej dwóch lat, pobyt stały albo pobyt rezydenta długoterminowego UE, to możesz ubiegać się dla nich o pobyt czasowy w celu połączenia z rodziną. Warto się do tego przygotować, by szansa na wspólny pobyt była większa. Nasze doświadczenie pozwoli Ci zminimalizować ewentualne przeszkody. Jest to bardzo ważne w perspektywie waszego przyszłego pobytu.'},
          {title: 'Pobyt rezydenta długoterminowego UE', value: 'Od Twojego przyjazdu minęło 5 lat, jesteś zatrudniony w Polsce, masz stałe, wystarczające i regularne dochody, wyjeżdżałeś wyłącznie służbowo albo odwiedzałeś rodzinę w ojczystym kraju lub spędzałeś urlop za granicą to czas kiedy warto zastanowić się nad uzyskaniem zezwolenia na pobyt rezydenta długoterminowego UE. Zyskujesz bezterminowe prawo pobytu w UE. Otwierasz nowe możliwości swym bliskim i możesz śmielej myśleć o obywatelstwie polskim.'},
          {title: 'Zezwolenie na pracę', value: 'Jeżeli pracujesz w Polsce, posiadasz zezwolenie na pracę oraz wizę lub zezwolenie na pobyt czasowy a twoja praca ma być kontynuowana to nie będziesz przedłużał zezwolenia na pracę i pobyt osobno tylko wystąpisz o zezwolenie na pobyt i pracę w ramach jednej procedury. Z tej procedury możesz również skorzystać jeśli chcesz rozpocząć pracę w Polsce.'},
          {title: 'Rejestracja pobytu obywatela UE', value: 'Jeśli jesteś obywatelem państwa należącego do UE i zamierzasz w Polsce przebywać dłużej niż 90 dni to masz obowiązek zarejestrowania swojego pobytu. Obowiązek ten dotyczy również członków rodziny towarzyszących Tobie podczas pobytu w Polsce. Jeśli Twój współmałżonek jest z kraju nienależącego do UE powinien wystąpić o wydanie karty pobytu członka rodziny obywatela UE. Pamiętaj, że swoje sprawy możesz powierzyć nam. Zaoszczędzisz cenny czas a Twoje zaangażowanie ograniczy się do niezbędnego minimum.'},
          {title: 'Karta pobytu członka rodziny obywatela UE', value: 'Jeśli jesteś w związku małżeńskim z obywatelem państwa należącego do UE lub EOG a sam nie posiadasz obywatelstwa państwa wymienionych organizacji oraz jeśli oboje zamierzacie pozostać w Polsce to powinniście pomyśleć o zalegalizowaniu pobytu. Ty możesz starać się o wydanie karty członka rodziny obywatela UE, a Twój współmałżonek powinien wystąpić o rejestrację pobyt obywatela UE. W obu przypadkach możemy Wam pomóc.'},
          {title: 'Pobyt stały obywatela UE', value: 'Jeżeli przebywasz w Polsce od 5 lat na podstawie zaświadczenia o zarejestrowaniu pobytu obywatela UE i nie opuszczałeś naszego pięknego kraju na dłużej niż 6 miesięcy w roku, to znaczy, że możesz starać się o pobyt stały. Jeśli opuściłeś Polskę na dłużej niż wspomniane 6 miesięcy, to nie musi to oznaczać, że straciłeś szansę. Jest wiele przyczyn, dla których musiałeś wyjechać, ale przerwy te nie będą miały wpływu na twój nieprzerwany pobyt i staranie się o pobyt stały. Zakładam, że razem z nami osiągniesz cel i będziesz mógł w niedługiej perspektywie pomyśleć o obywatelstwie polskim.'},
          {title: 'Pobyt stały członka rodziny obywatela UE', value: 'Jeśli przebywasz w Polsce od 5 lat na podstawie karty pobytu członka rodziny obywatela UE i nie opuszczałeś naszego pięknego kraju na dłużej niż 6 miesięcy w roku, to możesz starać się o pobyt stały. Jeśli opuściłeś Polskę na dłużej nie musi to oznaczać, że straciłeś szansę. Jest wiele przyczyn, dla których musiałeś wyjechać, ale przerwy te nie będą miały wpływu na twój nieprzerwany pobyt. Zakładam, że razem z nami otrzymasz stały pobyt i będziesz mógł w niedługiej perspektywie pomyśleć o obywatelstwie polskim. Możesz też pozostać przy pobycie stałym. Dajesz sobie wiele możliwości na przyszłość.'},
          {title: 'Audyt', value: 'Tą usługę kierujemy zarówno do Cudzoziemców jak i do firm, w których pracują Cudzoziemcy. Audyt dla Cudzoziemców przeprowadzany jest pod kątem możliwości uzyskania zezwoleń na pobyt rezydenta długoterminowego UE, czy uznania za obywatela polskiego. Audyt oprócz sprawdzenia czy Cudzoziemiec spełnia wymogi formalne będzie zawierał nasze uwagi co należy poprawić lub zmienić, żeby w przyszłości realizacja określonego celu była możliwa. Audyt dla firm związany jest z badaniem dokumentacji kadrowej pod kątem zgodności z przepisami regulującymi pracę i pobyt Cudzoziemców w Polsce. Nasze badanie kończy się sporządzeniem raportu. W przypadku stwierdzenia nieprawidłowości możecie państwo otrzymać nasze wsparcie w ich usunięciu.'},
          {title: 'Wykaz', value: 'Jeśli odmówiono Ci wizy lub nie zezwolono na wjazd do Polski, może to oznaczać, że Twoje dane są w wykazie cudzoziemców niepożądanych na terytorium Polski lub w Systemie Informacji Schengen. Aby to potwierdzić albo wykluczyć musisz mieć pełnomocnika, który będzie Ciebie reprezentował lub na którego adres będzie kierowana korespondencja zUrzędu do Spraw Cudzoziemców. Może okazać się że Twoje dane figurują systemie pomimo upływu terminu wpisu. W tej sytuacji możemy w twoim imieniu wystąpić o ich wykreślenie.'},
          {title: 'Doradztwo', value: 'Czasami będziesz miał wątpliwości, pojawią się pytania, otrzymana przez Ciebie decyzja będzie negatywna, zabraknie Ci pomysłów co zrobić lub nie będziesz pewny – możesz zawsze skonsultować się z nami. Doradzimy Ci, wyjaśnimy jakie są za i przeciw, pomożemy wybrać najlepsze rozwiązanie Twojego problemu. Z nami możesz zaplanować swoją przyszłość i przyszłość swoich bliskich. Dowiesz się na co zwrócić uwagę, żeby osiągnąć swój cel, którym może być między innymi uzyskanie stałego pobytu, statusu rezydenta czy polskiego obywatelstwa. Jeśli chcesz zrobić to szybko i bez zbędnej zwłoki zrób to z nami!'},

        ]
      }
    } else if(type === 'polish-courses') {
      return {
        description: [
          {title: 'Dlaczego my?', value: 'Wychodząc naprzeciw potrzebom i zainteresowaniom naszych klientów, poszerzyliśmy usługi o kursy języka polskiego, na które serdecznie wszystkich zapraszamy! \nCo czyni naszą ofertę wyjątkową?\nW obrębie prawa migracyjnego działamy już 17 lat i doskonale wiemy czego potrzebują nasi klienci w zakresie znajomości polskiej kultury i języka! Prowadzone przez nas kursy zostały opracowane z myślą o indywidualnym podejściu do Słuchacza. Program dostosowujemy więc do określonego przez Ciebie celu. \nTo co czyni naszą ofertę wyjątkową to zajęcia szyte na miarę!'},
          {title: 'Lektorzy', value: 'Nasi lektorzy to osoby doświadczone, od lat prowadzące zajęcia z języka polskiego dla\nObcokrajowców, które w przyjemnej atmosferze pomogą Ci nie tylko zgłębić tajniki języka, ale także wprowadzą Cię w kontekst społeczno-kulturowy Polski.\nProwadzimy zajęcia grupowe (2-6 osób) lub indywidualne w zależności od potrzeb.\nZgłoś się do nas, a otrzymasz ofertę na miarę Twoich potrzeb i możliwości!'},
          {title: 'Poziomy', value: 'A1 – A2\n\nWłaśnie przyjechałeś do Polski i chciałbyś nauczyć się podstawowych zwrotów, by czuć się komfortowo i bezpiecznie? Jesteś tutaj już jakiś czas, ale nie miałeś możliwości poznać naszej kultury i języka?\nZgłoś się do nas! Nauczymy Cię jak radzić sobie w codziennych sytuacjach!\nKurs na poziomie podstawowym polecamy osobom, dla których będzie to pierwsze lub jedno z pierwszych spotkań z językiem polskim!\nJeśli chcesz poznać podstawowe zwroty, które pozwolą Ci odnaleźć się w sklepie, na ulicy, w restauracji, czy w innych codziennych sytuacjach w trakcie Twojego krótkiego pobytu w Polsce ten kurs jest właśnie dla Ciebie!\nJeśli zamierzasz zostać w Polsce na dłużej będzie to doskonały wstęp do nauki języka na wyższych poziomach zaawansowania.\n\nB1 – B2\n\nJesteś w Polsce od dłuższego czasu a może właśnie przyjechałeś, ale język polski nie jest Ci całkiem obcy? W niedalekiej przyszłości chciałbyś zdawać egzaminy na studia w języku polskim lub myślisz o polskim obywatelstwie, ale nie jesteś pewien, czy Twoja znajomość języka będzie wystarczająca?\nZapraszamy na kurs na poziomie średniozaawansowanym! Dzięki naszym lekcjom będziesz bez przeszkód rozumiał zarówno tekst pisany jak i słuchany. Pozwolą Ci one również swobodnie konstruować wypowiedzi. Zyskasz zatem wiedzę niezbędną do zdania egzaminów, zarówno tych dotyczących obywatelstwa, jak i innych.\n\nC1 – C2\n\nMieszkasz i pracujesz w Polsce? Znasz dobrze język, ale chciałbyś, by polski był dla Ciebie prawie jak ojczysty? Może wymaga od Ciebie tego Twoja praca lub studia? Może po prostu zakochałeś się w naszej kulturze i chciałbyś kontynuować zgłębianie jej tajemnic poprzez naukę języka?\nZ przyjemnością Ci to umożliwimy, zapraszając do udziału w kursie na poziomie zaawansowanym.\nKurs pozwoli Ci nie tylko wypowiadać się płynnie i swobodnie, rozumieć nawet najbardziej skomplikowane artykuły prasowe, ale przede wszystkim da Ci pewność, że doskonale odnalazłeś się w nowym środowisku stając się jego częścią.'},
        ]
      }
     
    } else if(type ==='passport') {
      return {
        description: [
          {title: 'Nadanie obywatelstwa', value: 'Jeśli przebywasz w Polsce na podstawie pobytu czasowego, nie mówiąc już o pobycie stałym albo statusie rezydenta długoterminowego UE i masz ważny powód, dla którego chcesz stać się obywatelem polskim, masz prawo wystąpić do Prezydenta RP o nadanie obywatelstwa polskiego. Procedura jest na ogół długotrwała, a Prezydenta nie obowiązują żadne terminy. Pamiętaj, że sama chęć posiadania obywatelstwa na niewiele się tu zda. Dlatego wcześniej warto jest zasięgnąć naszej porady i ocenić własne szanse.'},
          {title: 'Uznanie obywatelstwa', value: 'Zakładam, że mieszkasz w Polsce na podstawie pobytu stałego albo rezydenta długoterminowego UE, mówisz dobrze po polsku, być może skończyłeś tu szkołę, masz stabilną pracę i myślisz o polskim obywatelstwie. To jest ten czas, kiedy możesz wystąpić o uznanie za obywatela polskiego. Jeśli uda się zrealizować ten cel pozostanie Ci jeszcze wystąpienie o dowód osobisty i paszport. Jak zawsze możesz na nas liczyć.'},
          {title: 'Przywrócenie obywatelstwa', value: 'Jeśli zostałeś pozbawiony obywatelstwa polskiego i dobrowolnie nie wstąpiłeś do służby wojskowej lub nie przyjąłeś urzędu publicznego w Państwach Osi lub ich sojuszników w okresie od 1 września 1939 r. do 8 maja 1945 r. i nie działałeś na szkodę państwa polskiego, to możesz starać się o przewrócenie obywatelstwa polskiego. Nabycie obywatelstwa tą drogą następuje z dniem uprawomocnienia się decyzji. Jeśli chcesz skorzystać z naszej pomocy prosimy o kontakt.'},
          {title: 'Potwierdzenie obywatelstwa', value: 'Jeśli wiesz, że w Twojej rodzinie ktoś pochodził z Polski, urodził się w Polsce, nosił polski mundur, chodził do polskiej szkoły, to być może posiadasz obywatelstwo polskie. Często jakiś niepozorny dokument, zdjęcie z rodzinnego archiwum może okazać się bezcenny do potwierdzenia obywatelstwa polskiego dla Ciebie i Twoich dzieci. Zawsze przed podjęciem się sprawy proponujemy klientom analizę dokumentów pod kątem określenia szans na uzyskanie potwierdzenia obywatelstwa. Jeśli chcesz skorzystać z naszej pomocy prosimy o kontakt.'},
          {title: 'Zrzeczenie obywatelstwa', value: 'W tym przypadku pomożemy Ci tylko wtedy, kiedy będziesz przekonany co do słuszności swojej decyzji i będziesz znał swoją sytuację, jeśli przestaniesz być obywatelem polskim.'},
        ]
      }
    } else if(type === 'business') {
      return {
        description: [
          {title: 'Zatrudnienie cudzoziemca', value: 'Czy planujesz zatrudnić cudzoziemca w swojej firmie? Firma deleguje do pracy w Polsce  pracownika pracującego obecnie w innym kraju lub cudzoziemiec został powołany do Zarządu spółki i większą część roku planuje przebywać w Polsce? We wszystkich tych przypadkach konieczne jest wystąpienie o udzielenie zezwolenia na pracę. Po uzyskaniu stosownego zezwolenia cudzoziemiec aplikuje o wizę z prawem do pracy w kraju stałego pobytu. Są przypadki, kiedy możliwe będzie również zatrudnienie cudzoziemca bez wizy. Tak to wygląda w telegraficznym skrócie, jednak załatwienie wszystkich spraw które pozwolą pracownikowi rozpocząć pracę może być bardzo skomplikowane i pochłonąć wiele Twojego czasu. Jeśli będziesz chciał możemy pomóc Tobie oraz Twojemu pracownikowi w znalezieniu optymalnego rozwiązania, uzyskaniu zezwolenia na pracę, wizy, znalezieniu mieszkania oraz w innych czynnościach związanych z pobytem.'},
          {title: 'Zakładanie', value: 'Jeśli chcesz prowadzić działalność, ale nie wiesz w jakiej formie, możesz skorzystać z naszego doradztwa. Przygotujemy wszystkie dokumenty i przeprowadzimy Cię przez proces rejestracji. Możemy zaproponować adres siedziby, a także przekazywać korespondencję pod wskazany przez Ciebie adres. Poprowadzimy księgowość i rozliczymy pracowników. Zajmiemy się sprawami legalizacji pobytu i pracy Cudzoziemców jeśli zamierzasz ich zatrudnić. Pomożemy Ci także w wielu innych sprawach. Zawszę będziemy z Tobą a co najmniej do momentu, kiedy rozwiniesz skrzydła. Pamiętaj, że możesz na nas liczyć. Tam, gdzie bezpośrednio nie będziemy mogli Ci pomóc, wskażemy kogoś, kto będzie mógł się tym zająć. Korzystamy z usług wyłącznie doświadczonych firm.'},
          {title: 'Sprzedaż', value: 'Jeśli chcesz szybko rozpocząć biznes w Polsce polecamy zakup zarejestrowanej Spółki. Oferowane przez nas Spółki nie są obciążone jakimikolwiek zobowiązaniami. Zostały utworzone z myślą o Tobie. Kupując od nas Spółkę możesz być pewny, że będzie ona dostosowana do Twoich potrzeb. Nie interesuje nas sama sprzedaż, gdzie różnych zmian będziesz musiał dokonywać sam lub za nie dopłacać. Interesuje nas Twoja satysfakcja i długotrwała współpraca w zakresie innych usług, które możemy zaproponować (więcej informacji w zakładce ZAKŁADANIE)'},
          {title: 'Zmiany', value: 'Prowadzisz działalność i chcesz dokonać zmiany? Dość często zdarza się, że zmiany te wymagają zgłoszenia do rejestru. Dotyczy to zarówno spółek kapitałowych jak i osobowych nie wyłączając działalności prowadzonej osobiście. By dokonać zmiany potrzebna jest odpowiednia forma i właściwe przygotowanie dokumentów. Obojętnie, czy będzie to zmiana adresu siedziby, nazwy, zarządu, wspólnika, przedmiotu działalności, podwyższenia lub obniżenia kapitału, czy przekształcenia, warto jest skorzystać z pomocy doświadczonego doradcy. Nasza firma pomoże Ci w przeprowadzeniu całego procesu szybko i skutecznie, a to tylko początek tego co możemy Ci zaoferować. Inne usługi znajdziesz w pozostałych zakładkach.'},
          {title: 'Rejestracja działalności gospodarczej', value: 'Rejestracja działalności to nie tylko „jedno okienko”. Jeżeli podjąłeś decyzję, że chcesz pracować na własny rachunek lub z jakiś powodów nie masz innego wyboru powinieneś od początku podejść do sprawy poważnie. Nie chodzi tu o wybór nazwy, co oczywiście też jest ważne, ale my mamy na myśli formę opodatkowania, prowadzenia dokumentacji księgowej, skorzystania z preferencyjnych warunków ubezpieczenia, dostosowania tego co chcesz robić do przedmiotu działalności, który będzie zgodny z PKD. Jest jeszcze wiele innych kwestii, które powinieneś rozważyć. Pamiętaj, że Twoja inwestycja szybko ma się zwrócić, podobnie jak poniesione na początku koszty. Działalność gospodarcza jest bardzo ciekawą formą prowadzenia biznesu dla tak zwanych „freelancerów” i nie dotyczy to tylko obywateli polskich, ale również Cudzoziemców będących obywatelami UE, Stanów Zjednoczonych oraz tych, którzy posiadają w Polsce status rezydenta, pobyt stały jak i zezwolenie na osiedlenie się. Jeśli podjąłeś decyzję zapraszamy Cię do kontaktu w celu omówienia szczegółów.'},
          {title: 'Wirtualne biuro', value: 'Dedykujemy wszystkim, którzy nie chcą ponosić dużych kosztów wynajmu pomieszczeń biurowych, a potrzebny im jest adres, pod który będzie kierowana korespondencja. Korespondencję odeślemy Tobie pocztą na wskazany przez Ciebie adres. Jeśli nas upoważnisz treść korespondencji otrzymasz również w wersji elektronicznej.\nUWAGA: klienci, którzy będą korzystać również usług księgowych lub obsługi Cudzoziemców mogą liczyć na ciekawe rabaty.'},
          {title: 'Pełna księgowość', value: 'Obsługa prowadzona w pełnym zakresie przez profesjonalistów. Zlecając nam prowadzenie księgowości w pełnym zakresie możesz skupić się na bieżącej działalności, oszczędzasz czas i nie musisz zatrudniać lub szkolić specjalistycznej kadry. Zakres podmiotów zobowiązanych do prowadzenia pełnej księgowości jest bardzo szeroki i oprócz osób prawnych (spółek z o.o., akcyjnych i komandytowo akcyjnych), oddziałów i przedstawicielstw firm zagranicznych bardzo często dotyczy spółek osobowych (spółek jawnych, partnerskich i komandytowych) oraz osób fizycznych prowadzących działalność gospodarczą.'},
          {title: 'Podatkowa księga przychodów i rozchodów', value: 'Ten uproszczony rodzaj ewidencji przeznaczony jest dla osób fizycznych prowadzących:\na) indywidualną działalność gospodarczą*)\nb) działalność gospodarczą w formie:\n- spółki cywilnej,\n- spółki jawnej,\n- spółki partnerskiej,\nktórych dochody z działalności gospodarczej opodatkowane są na zasadach ogólnych (podatek liniowy lub według skali podatkowej), jeśli ich przychody netto nie były równie lub przekroczyły kwoty 1 200 000 euro w przeliczeniu na polskie złote. Obsługę prowadzimy w pełnym zakresie uwzględniając indywidualne potrzeby i specyfikę prowadzonej przez naszych klientów działalności.\h*) dotyczy obywateli polskich i cudzoziemców państw członkowskich Unii Europejskiej, z państw członkowskich Europejskiego Stowarzyszenia Wolnego Handlu (EFTA) - stron umowy o Europejskim Obszarze Gospodarczym oraz osoby zagraniczne z państw niebędących stronami umowy o Europejskim Obszarze Gospodarczym, które mogą korzystać ze swobody przedsiębiorczości na podstawie umów zawartych przez te państwa z Unią Europejską i jej państwami członkowskimi.'},
          {title: 'Kadry i płace', value: 'Obsługa kadrowo – płacowa może być prowadzona kompleksowo jak i w wybranych aspektach kadr lub naliczaniem płac. Zapewniamy pełną obsługę spraw związanych z wynagrodzeniem pracowników poczynając od sporządzania listy płac i prowadzenia kartotek pracowników, po dokonywanie przelewów składek i prowadzenie rozliczeń z właściwymi urzędami (Urząd Skarbowy i Zakład Ubezpieczeń Społecznych). Nasz zakres obsługi kadrowej firm uwzględnia specyfikę związaną z wykonywaniem pracy przez cudzoziemców. Zajmujemy się również obsługą kadrowo płacową osób fizycznych zatrudniających pomoce domowe, opiekunki i pracowników fizycznych. Mamy również ciekawą ofertę dla osób wykonujących wolne zawody oraz pracę na podstawie umów o dzieło. Dokonujemy zgłoszeń do dobrowolnego ubezpieczenia zdrowotnego w NFZ (Narodowy Fundusz Zdrowia) i prowadzimy comiesięczną obsługę. Za naszym pośrednictwem możesz wystąpić o wydanie Europejskiej Karty Ubezpieczenia Zdrowotnego (EKUZ).'},
          {title: 'Rozliczenia roczne', value: 'Zeznania roczne, co do zasady składają wszyscy podatnicy w określonym dla różnych grup czasie. Dotyczy to zarówno rezydentów jak i nie rezydentów. Często z uwagi na złożoność, sprawy związane z przygotowaniem zeznania rocznego, popularnego PIT-u wymagają indywidualnego podejścia, co dotyczy zarówno obywateli polskich jak i cudzoziemców.'},
          {title: 'Wyprowadzanie zaległości', value: 'Usługa rozpoczyna się od przeprowadzenia audytu prowadzonej dokumentacji księgowej lub kadrowo płacowej, a następnie dokonaniu stosownych korekt i dostosowaniu jej do obowiązujących przepisów. Celem jest uniknięcie przez podatnika kary i zminimalizowanie następstw związanych z ujawnieniem nieprawidłowości przez organy kontroli skarbowej. Wyprowadzanie zaległości dotyczy aspektów księgowych i płacowych oraz zakresu ubezpieczeń.'},
          {title: 'Tłumaczenia', value: 'Przez lata obsługi Cudzoziemców z całego świata i związaną z tym koniecznością wykonywania różnego typu tłumaczeń udało nam się stworzyć bazę sprawdzonych i doświadczonych tłumaczy. Wykonujemy zarówno tłumaczenia zwykłe jak i przysięgłe, pisemne i ustne z i na wszystkie języki świata. Zawsze przed realizacją zlecenia określamy cenę, żeby nasz klient nie był nią zaskoczony. Nasze doświadczenie i szacunek dla klienta sprawił, że na pierwszym miejscu stawiamy zadowolenie tego drugiego z wykonanej pracy.'},

        ]
      }
    } else if(type === 'others') {
      return {
        description: [
          {title: 'Umiejscawianie aktów stanu cywilnego', value: 'Jest niezbędne przy wystąpieniu o obywatelstwo polskie, wydanie dowodu osobistego, paszportu, zezwolenia na pobyt czasowy wydanego ze względu na łączenie rodzin. Umiejscowienie polega na wpisaniu aktu urodzenia, małżeństwa, czy zgonu do polskich ksiąg stanu cywilnego. Należy pamiętać, że oryginał zagranicznego aktu pozostaje w polskich aktach. Możesz to zrobić sam, ale dla uniknięcia błędów w pisowni wynikających z transkrypcji powinieneś zdecydować się na pomoc specjalisty. Sprostowanie błędów możliwe jest w wielu przypadkach jedynie w postępowaniu sądowym.'},
          {title: 'Odpisy z urzędu stanu cywilnego', value: 'Odpisy będą Ci potrzebne w wielu sytuacjach. Począwszy od wystąpienia na zezwolenie na pobyt czasowy na podstawie łączenia rodzin a na polskim obywatelstwie i polskich dokumentach skończywszy (dowód osobisty, paszport). Odpis możesz otrzymać jako skrócony lub zupełny. Jeśli będziesz potrzebował odpisu do paszportu lub dowodu to taki odpis otrzymasz nie ponosząc opłat skarbowych. Jeśli nie masz czasu lub ochoty by się tym zająć to chętnie Ci pomożemy.'},
          {title: 'Uzupełnianie aktów stanu cywilnego', value: 'Jeżeli dokonałeś wpisu (umiejscowienia) aktu urodzenia lub małżeństwa, ale akt ten nie zawiera wszystkich wymaganych danych to będzie konieczne jego uzupełnienie. Najczęściej dotyczy to nazwiska panieńskiego ale nie tylko. Często przy uzupełnieniu okazuje się, że są rozbieżności dotyczące pisowni imion, nazwisk, lub innych danych zawartych w aktach sporządzonych w różnym czasie. Rozbieżności można sprostować na drodze sądowej. To jest moment kiedy powinieneś skorzystać z naszej pomocy.'},
          {title: 'Zaświadczenie z ZUS', value: 'Może być wydane jako zaświadczenie o braku zaległości lub jako zaświadczenie o wysokości podstawy, od której odprowadzono składki. Zaświadczenia te są często wymagane przy ubieganiu się o przedłużenie zezwolenia na pracę, legalizacji pobytu, procedurach przetargowych. O zaświadczenie możesz wystąpić sam lub przez nas. Zaświadczenie wydaje się w terminie do 7 dni, jeśli nie będą przy tym potrzebne dodatkowe wyjaśnienia.'},
          {title: 'Zaświadczenie z urzędu skarbowego', value: 'Może być wydane jako zaświadczenie o braku zaległości podatkowych lub jako zaświadczenie o dochodach. Zaświadczenia będą niezbędne w procesie legalizacji pobytu, szczególnie jeśli podstawą pobytu jest praca, a z pewnością jeśli posiadasz własną działalność. O zaświadczenie możesz wystąpić sam lub zwrócić się do nas. Zaświadczenie wydaje się w terminie do 7 dni, jeśli nie będą przy tym potrzebne dodatkowe wyjaśnienia.'},
          {title: 'Zaświadczenie z rejestru karnego', value: 'Może być Ci potrzebne przy ubieganiu się o pracę, wykonywaniu niektórych zawodów oraz przystąpieniu do przetargu. Jeśli będziesz potrzebował zaświadczenia, skontaktuj się z nami żeby je uzyskać.'},
          {title: 'Wypis z rejestru gruntów', value: 'Wypis będzie Ci potrzebny między innymi przy zakupie nieruchomości, do wniosku o wydanie zezwolenia na nabycie nieruchomości, czasami do kredytu. Z wypisu dowiesz kto jest właścicielem, jaka jest powierzchnia, czy działka jest budowlana czy rolna, czy dla nieruchomości prowadzona jest księga wieczysta. W każdej sytuacji kiedy wypis będzie Ci potrzebny skontaktuj się z nami.'},
          {title: 'Wypis z miejscowego planu zagospodarowania przestrzennego', value: 'Jeśli planujesz zakup jakieś działki warto wcześniej dowiedzieć się jakie są planowane inwestycje w okolicy, czy obok nie będzie przebiegała ruchliwa trasa, czy w Twojej okolicy nie powstaną budynki wielorodzinne, jeśli oczywiście chcesz być otoczony ciszą i spokojem. Wypis będzie Ci również potrzebny do wystąpienia o udzielenie zezwolenia na zakup nieruchomości, oczywiście w sytuacji jeśli zezwolenie będzie wymagane w Twoim przypadku wymagane. Jeżeli będziesz potrzebował pomocy skontaktuj się z nami.'},
          {title: 'Wypis z ksiąg wieczystych', value: 'Może być aktualny lub zupełny. Księgi wieczyste prowadzone są przez odpowiednie wydziały Sądów Rejonowych. Dowiesz się z nich kto jest właścicielem, jaka jest powierzchnia nieruchomości, czy nieruchomość jest zadłużona itp. Będziesz go potrzebował między innymi przy zakupie nieruchomości, wystąpieniu do MSWIA o pozwolenie na nabycie nieruchomości, czy zameldowaniu.  W każdej sytuacji możesz skontaktować się z nami w celu uzyskania wypisu w wersji poświadczonej. Wersje elektroniczną znajdziesz w Internecie (jest bezpłatna).'},
          {title: 'Wypis z KRS', value: 'To chyba najczęściej pobierany wypis. Dotyczy on podmiotów prowadzących działalność gospodarczą oraz stowarzyszeń i fundacji. Z niego dowiesz się wszystkiego o danym podmiocie, jego zarządzie, wysokości kapitału, przedmiocie działalności itp. Wypis może być aktualny lub zupełny. Najczęściej będzie Ci potrzebna wersja aktualna, chyba, że chcesz znać historię wszystkich wpisów. W każdej sytuacji możesz skontaktować się z nami w celu.'},
          {title: 'Zezwolenie z MSWiA', value: 'Jeśli jesteś Cudzoziemcem spoza UE upewnij się, czy do zakupu nieruchomości nie będzie konieczne uzyskanie zezwolenia MSWIA. W tej sprawie możesz skorzystać z naszego doradztwa. Decydując się na nasze usługi zaoszczędzisz czas. Jest to o tyle istotne, że sprzedający często nie chce długo czekać a Ty możesz być zobligowany do uzyskania stosownego zezwolenia. Jeśli w określonym czasie nie uzyskasz zezwolenia możesz stracić wpłacony zadatek, a sprzedający może odstąpić od umowy. Nasze usługi są kompleksowe i nie ograniczają się tylko do przygotowania wniosku. Możemy w Twoim imieniu kontaktować się ze zbywcą nieruchomości oraz innymi instytucjami w celu uzyskania niezbędnych dokumentów.'},
          {title: 'Zgłoszenie do dobrowolnego ubezpieczenia zdrowotnego', value: 'Jeśli nie posiadasz obywatelstwa UE i nie jesteś objęty obowiązkowym ubezpieczeniem zdrowotnym możesz skorzystać z dobrowolnego ubezpieczenia. Daje Ci to możliwość korzystania z placówek służby zdrowia oraz refundacji leków. Dodatkowo ubezpieczenie medyczne może być Ci potrzebne do legalizacji pobytu w Polsce. Możemy w Twoim imieniu zawrzeć stosowną umowę z Narodowym Funduszem Zdrowia oraz dokonywać co miesiąc odpowiednich płatności składek. Jeśli w Polsce przebywasz z rodziną możesz do ubezpieczenia dopisać rodzinę. Wtedy i ona będzie korzystała z powszechnego systemu opieki medycznej. Ubezpieczenie może być korzystne dla osób pracujących na podstawie umowy o dzieło, studentów, stażystów i kursantów.'},
          {title: 'Karty EKUZ', value: 'Jeśli jesteś ubezpieczony w zakresie powszechnego ubezpieczenia zdrowotnego i chcesz podróżować po UE to powinieneś posiadać kartę EKUZ, która potwierdza Twoje ubezpieczenie i prawo do korzystania ze świadczeń. Zakres świadczeń w poszczególnych krajach UE może się różnić. Przed wyjazdem dobrze jest zapoznać się z tymi instrukcjami. Warto też wykupić dodatkowe ubezpieczeniem medyczne, które obejmuje np. transport medyczny. Jeśli chcesz możemy uzyskać dla Ciebie kartę EKUZ, odpowiednie instrukcje a także dodatkowe ubezpieczenie medyczne.'},
  
        ]
      }
    
    }
    return {
      description: []
    }
  }

  const getEnglishTexts = (): TextsType => {
    if(type === 'immigrants'){
      return {
        description: [
          {title: 'Immigration to Poland', value: 'Do you want to settle down in Poland? Are you planning to start your work in Poland and maybe bring your family with you? Do you want to open new company and you associate your future with Poland? All matters related to immigration to another country can be very difficult for foreigners. Remember that you can entrust your case to us. Thanks to many years of experience, professional approach and commitment to each case we can help you with the legalization of both residence and work in Poland. With our help all administrative issues related to immigration to Poland will be conducted without any problems and you will have the opportunity and time to explore our beautiful country. Underneath you can find all matters that we can help you with..'},
          {title: 'Visas', value: 'If you are not eligible to travel to Poland on the Visa Waiver Program the entry and residence will take place on the appropriate visa. We can assist you in obtaining it: we will prepare a proposal, book an appointment in Polish Consulate, provide you with all necessary information. If you are planning a longer stay, you can continue it pursuant to an temporary permit.'},
          {title: 'Invitations', value: 'If there is someone who wants you to visit him/her in Poland or a company which for different reasons wants you to come you will need an invitation from them or visa. It demands a lot of commitment and time, which You often do not have. We can help you to obtain such an invitation and we will deal with all formalities. If you have an invitation, you can easily get a visa. We will willingly help you to get it.'},
          {title: 'Temporary residence card', value: 'As we suppose, you are here pursuant to the Visa Waiver Program or you have a visa or temporary residence permit and you decided to stay longer in Poland. The next appropriate step will be applying for a temporary residence permit and residence card. It is not easy and for many Foreigners is often a big challenge. It is high time to consider submitting to an experienced adviser pursue the case if you want to get a permanent residence permit in the future.'},
          {title: 'Family reunification', value: 'If you have left your family members in your motherland or they came to Poland and want to stay with you, and you have a temporary residence permit (card /s of temporary stay) for at least two years, permanent residence permit, EC residence permit for a long-term resident, you can apply for them for a temporary residence permit (KCP) in order to family reunification. It is worth to prepare for it - chance to spend time together will be greater. Our experience will allow you to minimize any obstacles. This is very important in the perspective of your future residence.'},
          {title: 'Permanent residence', value: 'If you are married to a Polish citizen or if you have Polish origin or you already have Card of Pole and you plan to settled down in Poland, it is worth thinking about permanent residence permit. You can also take care of your children’s future by applying for theirs permanent residence permit, if they born while you have been living in Poland pursuant to a temporary residence permit or permanent residence or EC residence permit for long-term resident. Thanks to permanent residence permit, you gain more rights and peace. You do not have to worry that decision will expired. You live calmer and you can implement your own plans. To make it happen take advantage of our services.'},
          {title: 'EC residence permit for a long-term resident', value: 'Five years have passed from your arrival to Poland, you have a fixed and regular income, you left Poland few times for business trips or to visit family in your motherland or you spent holidays abroad, it is a right time to consider obtaining a EC residence permit for a long-term resident. You gain the right to stay indefinitely in the European Union. Thanks to it you can open up new opportunities to your relatives, and you can start thinking about Polish citizenship.'},
          {title: 'Work permit in Poland', value: 'If you plan to start a job in Poland you should find an employer first. We suppose that you already have it or you would be seconded to work in Poland by your company. It can also happen that you will be appointed to the Management Board and you plan to stay in Poland for the most of the year. In all those cases the company you are or will be employed has to apply for work permit for you. When you receive it you will be able to apply for a visa with the right to work. This is how it looks in a nutshell. If you want to we can help you and your employer finding the best solution, getting a work permit, visa, finding accommodation and in other matters related.'},
          {title: 'Temporary residence permit and work permit', value: 'If you work in Poland and have a work permit and a visa or temporary residence permit and you continue your work in Poland, you can apply for a residence permit and a work permit within a single procedure. You can also choose this path if you want to start working in Poland. But, we definitely do not recommend this solution to foreigners who want to start working as soon as possible. This is related to the duration of the procedure (approximately 2 months). This process requires a personal appearance in the Office. Therefore, if you are planning to start work in Poland it, the best solution is to apply for a work permit on the basis of a visa with the right to work.'},
          {title: 'Registration certificate for the EU national', value: 'If you are a citizen of a country which belongs to the EU and you intend to stay in Poland longer than 90 days then you have to register your stay. This obligation also applies to family members accompanying you during your stay in Poland. If your spouse is from a country outside the EU, he/she should apply for a residence card of a family member of an EU citizen. Remember that you can entrust your case to us. You will save your valuable time and your commitment will be limited to the strict minimum.'},
          {title: 'EU family member’s residence card', value: 'If you are married to a national of a member state of the EU or EEA and you do not have the nationality of a member state of these organizations, and if you both are going to stay in Poland then you should think about the legalization of stay. You can apply for a EU family member’s residence card and your spouse should also register your stay (see registration of EU citizens). In both cases, we can help you.'},
         
          {title: 'Permanent stay for UE nationals', value: 'If you have been living in Poland for five years pursuant to certificate for the EU national and you have not left our beautiful country for more than 6 months a year, you can apply for permanent residence permit. If you left Poland for longer than mentioned 6 months, it does not necessarily mean that you havve lost your chance. There are many serious reasons why you had to leave Poland, but this break will not have an impact on your continuous residence permit. I assume that with us you will receive permanent residence and will be able to start thinking about Polish citizenship'},
          {title: 'Permanent stay for a family member of the EU national', value: 'If you have been living in Poland for five years with EU family member’s residence card have not left our beautiful country for more than 6 months a year, you can apply for permanent residence permit. If you left Poland for longer it does not necessarily mean that you have lost your chance. There are many serious reasons why you had to leave, but this break will not have an impact on your continuous residence. I assume that with us you will receive permanent residence and will be able to start thinking of Polish citizenship. You can also stay a permanent resident. Hence, you give yourself a lot of possibilities for the future. I wish you all the best but in life happens differently. That is why it is worth to have something which gives you confidence and a sense of independence.'},
          {title: 'Audit', value: 'This service is addressed both to foreigners and to the companies where foreigners work for. The audit is carried out in terms of the possibility of obtaining EC residence permit for a long-term resident or to be recognized as a Polish citizen. Audit, despite checking whether a Foreigner meets the formal requirements will include our comments concern what should be improved or changed in the future to make possible achieving particular goals. The audit for companies is carried out to check the compliance of personnel documentation with the law rules governing work and residence of foreigners in Poland. In the end of our analysis we will prepare a report. In case of finding irregularities, you can receive our support in their removal.'},
          {title: 'The list of foreigners whose residence in the territory of Poland is undesirable', value: 'If you were denied a visa or refused entry to Poland, it may mean that your data is on the list of undesirable foreigners on Polish territory or are in the Schengen Information System. In order to confirm or exclude it you will need to have an attorney who will represent you or to whom will be addressed correspondence from the Office for Foreigners. It may happen that your data are in the System despite the deadline of the entry has expired. In this situation we can apply on your behalf for the cancellation.'},
          {title: 'Consultancy', value: 'Sometimes you can have doubts or questions, you received a negative decision, you are run out of ideas what to do or you are not sure - you can always consult us. We will advise you, explain what are the pros and cons, we will help you to choose the best solution of your problem. With us you can plan your future and the future of your relatives. You will learn to what you should pay attention in order to achieve your goal, which can be for example: to obtain permanent residency permit, resident status, Polish citizenship. If you want to do it quickly and without a delay, do it with us. We do not experiment - we will tell how your situations looks like. The choice belongs to you.'},

        ]
      }
    } else if(type === 'polish-courses')  {
      return {
        description: [
          {title: 'Why with us?', value: 'To meet the needs and interests of our clients we decided to extend our services and offer you a wide variety of Polish language courses! Why our offer is so unique? We have operated for 17 years in the area of the migration law and we know exactly, what our clients need in terms of Polish language and culture! Our courses have been developed on the basis of individual needs of our students. Therefore we are always open to adapt the program to your specific goal! What makes our offer unique is tailor-made classes!'},
          {title: 'Teachers', value: 'Our teachers have years of experience in teaching foreigners Polish language. They will help you not only explore the secrets of the language, but also deal with the cultural and social aspects of living in Poland, all that in pleasant atmosphere. Depending on your needs, we offer classes in mini-groups (2-6 people) or individual lessons. Contact us and we will prepare an offer tailored to your needs and abilities!'},
          {title: 'Levels', value: 'To meet the needs and interests of our clients we decided to extend our services and offer you a wide variety of Polish language courses! Why our offer is so unique? We have operated for 17 years in the area of the migration law and we know exactly, what our clients need in terms of Polish language and culture! Our courses have been developed on the basis of individual needs of our students. Therefore we are always open to adapt the program to your specific goal! What makes our offer unique is tailor-made classes!'},
          {title: 'Why with us?', value: 'А1 – А2 \n\nYou have just arrived in Poland and would like to learn basic phrases to feel comfortable and safe? Or maybe you have been here for some time, but you did not have opportunity to learn about our culture and language? Contact us! We will teach you how to cope in everyday situations! We recommend the basic level course to those people for whom it will be their first or one of the first meetings with the Polish language!  If you want to learn the basic phrases that will help you do the shopping, order at a restaurant or cope with any other everyday situation during your short stay in Poland, this is course exactly for you! If you intend to stay in Poland for longer time, it will be an excellent introduction to learn language at higher level.\n\nВ1 – В2 \n\nYou have been in Poland for a long time or you have just arrived, but you are somehow familiar with the Polish language? In the near future you would like to take exams allowing you to study in Polish or you are thinking about obtaining Polish citizenship, but you are not sure whether your Polish good enough? Welcome to the course at the intermediate level! Thanks to these lessons you will not have any problems understanding written and oral texts. They will also allow you to easily express yourself. Therefore, you will gain the knowledge necessary to pass the exams, both those related to citizenship, as well as the others.\n\nC1 - C2 \n\nDo you live and work in Poland? You know Polish well, but it is not enough for you? Maybe your work or studies require mastering it? Or maybe you just felt in love with our culture and would like to continue exploring its secrets by learning the language? We will make it possible for you by inviting you to participate in the course at advanced level! This course will allow you to express yourself fluently and precisely and to understand even the most complex newspaper articles. Above all, it will give you the confidence that you have perfectly fit in the new environment by becoming a part of it.'},
        ]
      }
     
    } else if(type ==='passport') {
      return {
        description: [
          {title: 'Granting Polish citizenship by the President of the Republic of Poland', value: 'The President of the Republic of Poland can grant a foreigner, at his/her request, Polish citizenship. No conditions limit the constitutional competence of the Republic of Poland. The President can grant Polish citizenship to any foreigner. However, the citizenship granting procedure may be long lasting, because the President has no specific time frames to consider your request. You should remember that only the willingness to get a Polish citizenship is not sufficient. That is why it is worth to consult with us and to estimate your chances.'},
          {title: 'Recognition as a Polish citizen', value: 'We suppose that you have been living on the territory of Poland for few years pursuant to an temporary residence permit or a permanent residence permit or an EC residence permit for a long-term resident, you can speak Polish language or you probably finished school here, you have means of support and you think about Polish citizenship. This is the right moment to be recognized as a Polish citizen. If you are successful on this field you only have to apply for Polish identity card and passport. As always we are with you and you can count on us.'},
          {title: 'Restoration of Polish citizenship', value: 'If you lost a Polish citizenship and you did not join the army voluntary or you did not occupied a position in a public office in The Axis powers or in their allies during the period from September 1, 1939 to May 8, 1945 and you did not act against a Polish state, you can apply for restoring polish citizenship. Acquisition of citizenship in this way following the day on which the decision is validated. If you need our assistance please contact us.'},
          {title: 'Confirmation of Polish citizenship', value: 'If you know that somebody of your relatives came from Poland, were born here, dressed a Polish uniform, attended a Polish school, you maybe have a Polish citizenship. It is quite often that an insignificant document, a photo from your family archive may turn out to be invaluable in confirming Polish citizenship for you and your kids. Always before taking up the matter, we offer customers the analysis of documents in order to estimate the chances of obtaining the confirmation of citizenship. If you need our assistance please contact us.'},
          {title: 'Renunciation of Polish citizenship', value: 'In this case we can help you only if you are convinced that your decision is right and you know the consequences of renunciation of Polish citizenship.'},
        ]
      }
    } else if(type === 'business') {
      return {
        description: [
          {title: 'Company formation in Poland', value: 'If you want to run a business, but you do not know which form you should choose, you can ask for our advice. We will prepare all documents and help you to go through company formation in Poland. We offer registered office address, but we can also send correspondence to the address specified by you. We will deal with all matters concerning the legalization of work and stay for your foreign employees if you want to hire them. We will help you in many other cases. Remember that you can count on us. If we can not directly help you, we will indicate someone who will be able to deal with your problems.'},
          {title: 'Selling a company', value: 'If you want to quickly start a business in Poland, we recommend the purchase of the  Company which has already been registered. companies offered us are not burdened by any obligations. If you buy a company from us you can be sure that it will be tailored to your needs. We are not only interested in selling the company, but also in your satisfaction and long-term cooperation in the field of the other services that we can offer.'},
          {title: 'Changes', value: 'Do you run a  business and you want to change something? It frequently happens that these changes need to be notified to the register. This applies to both limited liability companies and partnerships and also to the activities carried out in person. To make the changes you need a proper form and proper preparation of documents. Whether it will be a change of address, name, board, partner, business profile, increase or decrease in capital or transformation, it is worthwhile to use the help of an experienced adviser. Our company will help you go through the complete process quickly and efficiently, and this is just the beginning of what we can offer.'},
          {title: 'Business Registration', value: 'There is no possibility to register an economic activity on the principle of "one window" in Poland. If you decided to start your own business, then you have to consider your decision seriously from the very beginning.  The most significant thing is to choose the right form of taxation, accounting, insurance conditions, etc. Of course, there are many other issues that you should think about, however you have to remember that your investment should be returned and should start to be profitable as soon as possible.\nAn economic activity is a very interesting form of business for so-called "freelancers", and it applies not only to Polish citizens, but also foreigners who are the citizens of the European Union and the US, or those who have a resident status, a residence or a settlement permit in Poland. If you decided to register any kind of economic activity, feel free to contact us. We can discuss all the details together. '},
          {title: 'Virtual Office', value: 'Virtual Office is a convenient and economically rational form of running business for anyone who does not want to bear the high costs of office rent. We can receive and send your correspondence to the specified address. However, if you are interested in obtaining it in electronic form, we can open, scan and send all your mail notifications via email.'},
          {title: 'Complete Reporting form', value: 'The service is realizing in complete scope. Handing us maintain the complete reporting form, you can pay attention to the current activities of the company, as you no longer need to hire or train new employees, what in fact saves your valuable time. The list of subjects required to maintain complete reporting form is very long.  Aside from legal entities (limited liability companies, joint-stock companies and limited (kommendit) companionship), branches and representative offices of foreign companies, more often than not also applies of partnerships (general partnerships and limited partnerships) and individuals, realizing business activities.'},
          {title: 'Revenue and Expenditure', value: 'This is simple type of records intended for individuals who engaged in: a) Individual business activity *The business activity in the form of:\n- A general partnership,\n- A full opening partnership,\n- Partnership\nWhose incomes of entrepreneurial activities is impose a tax according of the general rules (proportional or progressive taxation) if their net revenue is not accounted ≥ 1 200 000 EUR in PLN. We provide this service in complete scope relying on the individual needs and characteristics of business activities of our clients.\n\n* Refers to the Polish citizens and nationals of the Member States of the European Union, the members of the European Free Trade Association (EFTA) - parties to the Agreement on\n\nEEA and foreign persons from countries which are not party to the Agreement on the European Economic Area, which derive benefit from the freedom of entrepreneurial activity based on agreements concluded by further States to the European Union and individual members'},
          {title: 'HR and Payroll Services', value: 'Service can be carried out comprehensively or in selected aspects of human resources or payroll. We provide full service of remuneration of employees like payroll records and conducting personnel files. We also transfer contributions and deal with relevant authorities (Tax Office and Social Insurance Office). Providing our HR services we take into consideration the specificity of hiring foreigners. We also support individuals employing domestic servants, nannies and workers. We also have an interesting offer for members of the liberal professions and work under contracts. We make submissions to voluntary health insurance in the NFZ (National Health Fund) and conduct a monthly service. With our help you can apply for a European Health Insurance Card (EHIC).'},
          {title: 'Annual tax declarations', value: 'All taxpayers at a specific time for the different groups have to submit the annual tax declarations. This applies to both residents and non-residents. Often, due to the complexity of the issues associated with the preparation of annual tax declaration, a popular PIT require an individual approach, which applies to both Polish citizens and foreigners.'},
          {title: 'Balancing books', value: 'The service begins with the audit of the accounting records or personnel payroll and finishes with making appropriate adjustments and adapting them to the existing legislation. The aim is to avoid the pay by taxpayer penalties and minimize the consequences associated with the discovery of irregularities by the tax authorities.  Balancing books focuses on the accounting and payroll, and the scope of insurance.'},
          {title: 'Translations', value: 'Thanks to our experience gained while serving foreigners from around the world and we have created a database of proven and experienced translators. We translate both regular and certified, written and oral from and into all the languages of the world. We always specify the price before translating which means that our clients are never surprised by it. Our experience and respect for the customer made in the first place we put the satisfaction of the latter with the work done.'},

        ]
      }
    } else if(type === 'others') {
      return {
        description: [
          {title: 'Registration of vital records', value: 'The registration is necessary to obtain a Polish citizenship, identity card, passport, temporary residence permit issued due to family reunification. The registration consists in putting birth, marriage, or death certificate into the Polish civil registry. Please note that the original foreign certificate stays in Polish civil registry. You can register acts by yourself, but you had better avoid transcription errors, so you should ask for professional help. Correcting the errors is often possible only in court.'},
          {title: 'A copy from the public registrar’s office', value: 'The copy of the vital records will be needed in many situations. Starting from residence permit based on family reunification, Polish citizenship and Polish documents. There are two different kinds of copies: complete and condensed which does not contain all information. If you need a copy of a passport or a copy of an ID, it is available free of charge. If you do not have the time or desire to take care of it, we will be happy to assist you.'},
          {title: 'Amending data in the public registrar’s office', value: 'If you have registered your birth or marriage certificate, but the certificate does not contain all required data, it will be necessary to complete it. Mostly it concerns maiden name but not only. It often turns out that there are some differences regarding the spelling of names, surnames, or other information contained in certificates which were registered at different times. The differences can be corrected only by the court. This is the moment when you should take advantage of our help.'},
          {title: 'A certificate from the Social Insurance Institution (ZUS)', value: 'It may be issued as a clearance certificate or a certificate of the base amount from which social security contribution is paid. These certificates are often required when applying for renewal of a work permit, legalization of stay or tendering procedures. You can get the certificate by yourself or we can help you do it. The certificate is issued within 7 days if further clarification is not required.'},
          {title: 'A certificate from the Tax Office', value: 'It may be issued as a certificate of tax clearance or as proof of income. Certificates will be needed when legalizing your stay in Poland, especially if the basis for the stay is work, and certainly if you run your own business. You can try to obtain certificate without any help or ask us to do it for you. The certificate is issued within 7 days if further clarification is not required.'},
          {title: 'A certificate from the National Criminal Register', value: 'You will need it when applying for work permit as it is required in some professions and when participating in the tender. If you need it, please contact us.'},
          {title: 'An extract from the land register', value: 'You will need it when buying real estate or applying for a permit to do it, sometimes when asking for a loan. Thanks to it you will know who the owner of the real estate is, how big it is, or whether it is a building or agricultural plot, or if it has a real-estate register. Anyway, you can always contact us.'},
          {title: 'An extract from the urban local spatial management plan', value: 'If you plan to purchase a plot, it is worth to find out beforehand if next to your house a busy route or multi-family buildings are going to be built. Do this only if you want to be surrounded by peace and tranquility. You will also need it if a special permission is required to buy a from Home Office. In each of these cases, you can contact us to assist you.'},
          {title: 'An extract from the real-estate register', value: 'It may be either current or complete. Real-estate registers are run by relevant departments of district courts. You will learn from them who the owner is, what the area of ​the property is, whether the property is indebted, or if there is dirt on the property, etc. You will need it when buying a property, applying to the Ministry of the Interior for a permit to purchase real estate, when registering a tenant, etc. In each situation you can contact us to obtain a certified version of the extract. You can print the electronic version yourself from the Internet.'},
          {title: 'An extract from the National Court Register', value: 'This is probably the most popular extract. It applies to businesses, associations and foundations. Thanks to it you will learn everything about the entity, its board of directors, registered capital and core activities, etc. The extract may be either current or complete. Most often you will need the current version, unless you want to know the history of all entries. You can contact us if you want to obtain a certified extract. The electronic version is free of charge and you can find it on the Internet.'},
          {title: 'A permit to buy real estate from the Ministry of the Interior', value: 'If you are non-EU citizen, make sure that you will not need a special permit from Home Office to buy real estate. We can advise you on this matter. If you decide on our service, you will save your time for sure. It is important if the seller cannot wait for a long time and you are obliged to obtain a special permit. If you do not get it, you can easily lose the deposit you paid and the seller may withdraw from the contract. We can help you not only to prepare the application, but also we can contact the seller and other institutions on your behalf to collect all necessary documents.'},
          {title: 'Applying for a public health insurance', value: 'If you are not a UE citizen and you are not obliged to possess a compulsory health insurance, you can opt for voluntary insurance. This gives you the ability to use health facilities and to reimburse medicines. In addition, medical insurance may be needed to legalize your stay in Poland. We can conclude an agreement with the National Health Fund on your behalf and make appropriate monthly payments. If you are in Poland with your family, you can include your relatives in the insurance. Then they will also be able to use the public health care system. The insurance can be beneficial especially for people working under contract of commission, students, trainees and foreigners learning the Polish language.'},
          {title: 'EHIC cards', value: 'If you possess a public health insurance and you want to travel in the UE, you should ask for an European Health Insurance Card (EHIC), as it proves that you are insured and you have the right to use medical services. The range of services in different EU countries may vary. Before traveling, it is good to be familiar with these instructions. You should also opt for an additional medical insurance that covers such services as medical transport. If you want we can get for you the EHIC card, proper instructions and additional medical insurance.'},
  
        ]
      }
    
    }
    
    else {
      return {
        description: [
          {title: 'Why with us?', value: 'To meet the needs and interests of our clients we decided to extend our services and offer you a wide variety of Polish language courses! Why our offer is so unique? We have operated for 17 years in the area of the migration law and we know exactly, what our clients need in terms of Polish language and culture! Our courses have been developed on the basis of individual needs of our students. Therefore we are always open to adapt the program to your specific goal! What makes our offer unique is tailor-made classes!'},
          {title: 'Teachers', value: 'Our teachers have years of experience in teaching foreigners Polish language. They will help you not only explore the secrets of the language, but also deal with the cultural and social aspects of living in Poland, all that in pleasant atmosphere. Depending on your needs, we offer classes in mini-groups (2-6 people) or individual lessons. Contact us and we will prepare an offer tailored to your needs and abilities!'},
          {title: 'Levels', value: 'To meet the needs and interests of our clients we decided to extend our services and offer you a wide variety of Polish language courses! Why our offer is so unique? We have operated for 17 years in the area of the migration law and we know exactly, what our clients need in terms of Polish language and culture! Our courses have been developed on the basis of individual needs of our students. Therefore we are always open to adapt the program to your specific goal! What makes our offer unique is tailor-made classes!'},
          {title: 'Why with us?', value: 'А1 – А2 You have just arrived in Poland and would like to learn basic phrases to feel comfortable and safe? Or maybe you have been here for some time, but you did not have opportunity to learn about our culture and language? Contact us! We will teach you how to cope in everyday situations! We recommend the basic level course to those people for whom it will be their first or one of the first meetings with the Polish language!  If you want to learn the basic phrases that will help you do the shopping, order at a restaurant or cope with any other everyday situation during your short stay in Poland, this is course exactly for you! If you intend to stay in Poland for longer time, it will be an excellent introduction to learn language at higher level. В1 – В2 You have been in Poland for a long time or you have just arrived, but you are somehow familiar with the Polish language? In the near future you would like to take exams allowing you to study in Polish or you are thinking about obtaining Polish citizenship, but you are not sure whether your Polish good enough? Welcome to the course at the intermediate level! Thanks to these lessons you will not have any problems understanding written and oral texts. They will also allow you to easily express yourself. Therefore, you will gain the knowledge necessary to pass the exams, both those related to citizenship, as well as the others. C1 - C2 Do you live and work in Poland? You know Polish well, but it is not enough for you? Maybe your work or studies require mastering it? Or maybe you just felt in love with our culture and would like to continue exploring its secrets by learning the language? We will make it possible for you by inviting you to participate in the course at advanced level! This course will allow you to express yourself fluently and precisely and to understand even the most complex newspaper articles. Above all, it will give you the confidence that you have perfectly fit in the new environment by becoming a part of it.'},
        ]
    }
  }
}

  const descriptions = isPl ? getPolishTexts().description : getEnglishTexts().description;
  if(setModalOpen === undefined) {
    return null;
  }
  return (
    <div>
      <Modal open={modalType !== null} onClose={() => setModalOpen(null)} center>
        <Heading>{isPl ? getPolishTitle() : getEnglishTitle()}</Heading>
        <div>{descriptions.map(e => {
          return (<div>
            <Subtitle>{e.title}</Subtitle>
            <Description>{e.value}</Description>
          </div>)
        })}</div>
      </Modal>
    </div>
  );
};